### ISSUE TITLE
Is there a way to format or parse Datepicker value ?

### ISSUE THREAD

**Issue by TatoCuervo** [stackworx/formik-mui#157]
Im trying to use 

`<Field component={KeyboardDatePicker} label="label" name="date" />;`

and would like to set the selected date value to formik state(in this example would be 'date') in the format 'dd/mm/yyyy'.

Is it possible to do that?

**Comment by dieguezz** [comment]
@TatoCuervo  Read the documentation in @material-ui/pickers, you will see you got a `format` prop. https://material-ui-pickers.dev/api/KeyboardDatePicker

**Comment by TatoCuervo** [comment]
> @TatoCuervo Read the documentation in @material-ui/pickers, you will see you got a `format` prop. https://material-ui-pickers.dev/api/KeyboardDatePicker

Thanks @dieguezz , I've actually tried that one but it is only for displaying the value. The actual value set to the form by the component it's not being formatted.

**Comment by dieguezz** [comment]
@TatoCuervo i am pretty sure i got a similar use case like yours. What we do is work with real dates in their original format always. So i'd store the normal date in formik, and then, when consuming it, i'd use some kind of [date-fns](https://date-fns.org/)to paint it or transform it according to the correct locale.
