### ISSUE TITLE
Firefox behavior with KeyboardDatePicker on invalid Date

### ISSUE THREAD

**Issue by dieguezz** [stackworx/formik-mui#213]
## Description

In Firefox, when you fill in an invalid date in a keyboardDatePicker, then the date you filled is changed automatically.

## Steps to reproduce:

1.  Go to https://codesandbox.io/s/keyboarddatepicker-invalid-firefox-b1b7l
2. Fill in an invalid date like ` 11/11/1111`
3. Your date value has changed to `10/11/1111`

**Comment by dieguezz** [comment]
I just updated all deps and this is still happening in firefox

![input](https://user-images.githubusercontent.com/1161455/139810567-01f33186-2109-4c20-8f96-36e8170d0888.gif)

**Comment by cliedeman** [comment]
Hi

**Comment by dieguezz** [comment]
Closing as i am not updating the sandbox (2 year later) and i dont use formik anymore
