### ISSUE TITLE
What is the method of clearing autocomplete data?

### ISSUE THREAD

**Issue by choyan** [stackworx/formik-mui#219]
I am using formik-material autocomplete component. After `onSubmit` method I am trying to clear the form. 

```
onSubmit={(values, actions) => {
  setTimeout(() => {
    submitData(values);
  }, 500);
  actions.setSubmitting(false)
  actions.resetForm()
}}
```

Rest if the fields are being cleared properly. But the autocomplete enabled forms are not clearing.

**Comment by cliedeman** [comment]
@choyan I have have updated the codesandbox to include a reset button and this works as expected
