### ISSUE TITLE
Should set name for Autocomplete TextField

### ISSUE THREAD

**Issue by aiingstan** [stackworx/formik-mui#225]
I followed the package's documentation site: https://stackworx.github.io/formik-material-ui/docs/api/material-ui-lab#autocomplete to create an Autocomplete component, then I found after I touched the input, the `touched` value of the `Formik` instance is changing, however, using an unexpected field name like `mui-xxxx`.

This is causing the expression `touched['name']` always return `false`, so the error message is not styled.

I added a name property to the `TextField`, then it works fine. Is this some known issue of this package, or am I missing something?

**Comment by jmcpeak** [comment]
I noticed the same thing, but a work around for now is to pass an `id="customNameHere"` prop on `Autocomplete`.

That makes it work.

**Comment by cliedeman** [comment]
This seems like a docs issue as we actually have zero control over what the user puts in the renderInput function
