### ISSUE TITLE
RadioGroup + FormControlLabel can't handle boolean

### ISSUE THREAD

**Issue by giacomocalianno** [stackworx/formik-mui#292]
Hi, when i click on a radio FormControlLabel i need to set my variable to true or false, but i can only put strings in the value field.
![Screenshot_2](https://user-images.githubusercontent.com/66018682/134945703-43b2f946-950f-4f8a-9ccd-dd3add4e9ba5.png)

**Comment by johandieman** [comment]
@giacomocalianno please elaborate on the issue, Boolean(mystring) should suffice as a bool conversion.
