### ISSUE TITLE
The `Select` component doesn't adapt the label to the used variant

### ISSUE THREAD

**Issue by TiredFalcon** [stackworx/formik-mui#311]
## Current Behavior 😯

The label of the `Select` component displays wrongly if I use `variant="standard"`. The label is displayed as if the variant were `"outlined"`.  Moreover, the component doesn't respect the `fullWidth` prop, and instead only grows to the size of whatever value is displayed.

## Expected Behavior 🤔

The label of the `Select` component should display according to the used variant. The `fullWidth` prop should be respected.

## Steps to Reproduce 🕹

Here is an example using the `Select` component, which shows its problems. Below it, I used a `TextField` with the `select` prop to show the expected behavior.

[CodeSandbox](https://codesandbox.io/s/fancy-silence-43och?file=/src/index.tsx)

**Comment by martin-trajanovski** [comment]
@TiredFalcon I think it is now well documented but if you check `Select` props type you can see that you probably need to use something like this: 
`
  <Field
      component={Select}
      formControl={{
        fullWidth: true,
        variant: 'standard',
      }}
      inputLabel={{
        variant: 'standard',
      }}
    >
      {instrumentScientists.users.map((user, i) => (
        <MenuItem value={user.id} key={i}>
          {getFullUserName(user)}
        </MenuItem>
      ))}
    </Field>
`

**Comment by TiredFalcon** [comment]
This seems to work perfectly, thanks!

You're also right that should be better documented though.
