### ISSUE TITLE
TextField label gets in the way with initial Chrome autofill value

### ISSUE THREAD

**Issue by SoulDancer27** [stackworx/formik-mui#362]
It might be, that I just don't know how to do it properly, this issue appeared after i moved to mui-v5. If the value for the TextField component is taken from browser autofill value the label initially lays right on top of it covering the text. After i click on the form it moves to the top where it should be. 

![image](https://user-images.githubusercontent.com/34806883/227955532-e60fdbf9-89cd-4109-ba29-73fe66468c3d.png)
![image](https://user-images.githubusercontent.com/34806883/227955632-ace23007-f57c-4e78-87a7-6e659c40ebcf.png)

How should I address this issue? 
The code looks like this:
```
  <Field
                  component={TextField}
                  name="name"
                  variant="outlined"
                  label={
                    <Typography variant="body1" color="textPrimary">
                      Логин
                    </Typography>
                  }
                  fullWidth
                  className={classes.textfield}
                />
```

Any help would be appreciated

**Comment by cliedeman** [comment]
You can shrink the label.

https://mui.com/material-ui/api/input-label/#input-label-prop-shrink
Not much you can really do about the auto fill. But this is a general mui issue
