### ISSUE TITLE
formik-mui-x-date-pickers - The `renderInput` has been replaced by an input component slot props

### ISSUE THREAD

**Issue by jmcpeak** [stackworx/formik-mui#368]
## Current Behavior 😯

When using the DatePicker wrapper, a warning is oupt to the console: 

```
The `renderInput` prop has been removed in version 6.0 of the Date and Time Pickers.
You can replace it with the `textField` component slot in most cases.
For more information, please have a look at the migration guide (https://mui.com/x/migration/migration-pickers-v5/#input-renderer-required-in-v5). 
    at DesktopDatePicker (https://localhost.collegeboard.org:3000/_next/static/chunks/node_modules_@mui_x-date-pickers_f67c68._.js:10225:219)
    at DatePicker (https://localhost.collegeboard.org:3000/_next/static/chunks/node_modules_@mui_x-date-pickers_f67c68._.js:11209:239)
```

## Expected Behavior 🤔

No console message should be logged
https://mui.com/x/migration/migration-pickers-v5/#input-renderer-required-in-v5

## Steps to Reproduce 🕹

Open the console here:
https://codesandbox.io/p/sandbox/silent-rain-v3lzql

**Comment by jmcpeak** [comment]
I'm going to try and get a PR going tomorrow to fix this

**Comment by nattyg93** [comment]
@jmcpeak Were you able to write this PR?

**Comment by jmcpeak** [comment]
I finally have time to look at this, sponsored by my employer. Will report back soon.
